openapi: 3.0.0
info:
  title: Sample Spec First api
  version: "1.0"

paths:
  /:
    get:
      operationId: getIndex
      responses:
        "200":
          description: API is up
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
  /hello:
    get:
      operationId: getHello
      responses:
        "200":
          description: Say hello
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
