openapi: 3.0.0
info:
  title: Sample Spec First api
  version: "1.0"

paths:
  /:
    get:
      operationId: getIndex
      responses:
        "200":
          description: API is up
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

  /user:
    get:
      operationId: getUser
      responses:
        "200":
          description: Get user
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                required:
                  - id
